import type { Metadata } from "next";
import { Inter, Vazirmatn, Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const vazir = Vazirmatn({ subsets: ["arabic", "latin", "latin-ext"] });
const kufi = Noto_Kufi_Arabic({ subsets: ["arabic"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
